quartz:
  enable: true
server:
  port: 9090
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/chinaQuartz
    username: root
    password: 1234
#    tomcat:
#      initialSize: 20
#      maxActive: 100
#      maxIdle: 100
#      minIdle: 20
#      maxWait: 10000
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    cache: false

#引入日志配置文件
##=====================================  log  =============================
#logging:
#  config: classpath:log4j2.xml
